---
mass: &mass 1.0
hbar: &hbar 1.0

##GRID##
T: 2
ntime: 1000

N: 512
xstart: -20
xstop_or_dx: 20.0 #if endpoint_mode, then this is xstop
endpoint_mode: True
#######

nonlinear: True

potential:
  type: nonlinear_potential
  params:
    mass: *mass
    hbar: *hbar
    beta: 1.0

wavefunction:
  type: bright_soliton
  params:
    amp: 1.0
    v: 1.0
    mass: *mass
    hbar: *hbar
