---
mass: &mass 1.0
hbar: &hbar 1.0

##GRID##
T: 60
ntime: 1000

N: 1024
xstart: -10
xstop_or_dx: 10.0 #if endpoint_mode, then this is xstop
endpoint_mode: True
#######

nonlinear: True

save: True 
base_file_name: bright_soliton_fixed

potential:
  type: nonlinear_potential
  params:
    mass: *mass
    hbar: *hbar
    beta: -1.0

wavefunction:
  type: bright_soliton
  params:
    amp: 0.5
    v: 2.0
    mass: *mass
    hbar: *hbar
