---
mass: &mass 1.0
hbar: &hbar 1.0
omega: &omega 1.0
##GRID##
T: 100
ntime: 1000

N: 1024
xstart: -10
xstop_or_dx: 10.0 #if endpoint_mode, then this is xstop
endpoint_mode: True
#######

nonlinear: False

save: True
base_file_name: qho_ground_state

potential:
  type: harmonic_potential
  params:
    mass: *mass
    hbar: *hbar
    omega: *omega

wavefunction:
  type: energy_eigenstate
  params:
    level: 0
    mass: *mass
    hbar: *hbar
    omega: *omega
